[project]
name = "mcp-postgres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.0.0",
    "psycopg2-binary>=2.9.0",
    "asyncpg>=0.28.0",
    "matplotlib>=3.10.5",
]
